{% set name = "peppy" %}
{% set version = "0.40.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22ed51ae042ec2e1fbfa213205967133319fa498a7f09aa438eccfebfae5e78f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attmap >=0.12.5
    - python >=3.6
    - pyyaml >=5
    - ubiquerg >=0.5.2
    - pandas >=0.24.2
    - logmuse >=0.2
    - rich

test:
  imports:
    - peppy

about:
  home: https://github.com/pepkit/peppy/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Project metadata manager for PEPs in Python

extra:
  recipe-maintainers:
    - stolarczyk
